"""pi-py-sdk: Python SDK for the Pi coding agent over its RPC bridge.

Drives ``pi --mode rpc`` (the well-tested ``pi-agent-core`` runtime) as a subprocess,
exposing an async Python API. No agent logic is reimplemented in Python.
"""

from __future__ import annotations

from .client import PiAgent, UiHandler, UiResult
from .config import PiConfig
from .model import PiModelClient
from .sync import PiAgentSync, PiModelClientSync
from .errors import (
    PiCommandError,
    PiError,
    PiModelError,
    PiNotStartedError,
    PiProcessError,
    PiTimeoutError,
)
from .protocol import (
    DIALOG_METHODS,
    STREAM_TERMINAL_TYPES,
    AgentEndEvent,
    AgentStartEvent,
    AssistantMessage,
    AssistantMessageEvent,
    AutoRetryEndEvent,
    AutoRetryStartEvent,
    BashExecutionMessage,
    CompactionEndEvent,
    CompactionStartEvent,
    Event,
    ExtensionErrorEvent,
    ExtensionUIRequest,
    ImageContent,
    MessageEndEvent,
    MessageStartEvent,
    MessageUpdateEvent,
    QueueUpdateEvent,
    Response,
    SessionInfoChangedEvent,
    StreamEvent,
    TextContent,
    ThinkingContent,
    ThinkingLevelChangedEvent,
    ToolCall,
    ToolExecutionEndEvent,
    ToolExecutionStartEvent,
    ToolExecutionUpdateEvent,
    ToolResultMessage,
    TurnEndEvent,
    UserMessage,
    message_text,
    parse_event,
    parse_message,
    parse_messages,
    parse_stream_event,
)

__version__ = "0.2.0"

__all__ = [
    "PiAgent",
    "PiAgentSync",
    "PiModelClient",
    "PiModelClientSync",
    "PiConfig",
    "UiHandler",
    "UiResult",
    "PiError",
    "PiNotStartedError",
    "PiProcessError",
    "PiTimeoutError",
    "PiCommandError",
    "PiModelError",
    "Event",
    "AgentStartEvent",
    "AgentEndEvent",
    "AssistantMessageEvent",
    "MessageStartEvent",
    "MessageUpdateEvent",
    "MessageEndEvent",
    "TurnEndEvent",
    "ToolExecutionStartEvent",
    "ToolExecutionUpdateEvent",
    "ToolExecutionEndEvent",
    "QueueUpdateEvent",
    "CompactionStartEvent",
    "CompactionEndEvent",
    "AutoRetryStartEvent",
    "AutoRetryEndEvent",
    "SessionInfoChangedEvent",
    "ThinkingLevelChangedEvent",
    "ExtensionErrorEvent",
    "ExtensionUIRequest",
    "DIALOG_METHODS",
    "StreamEvent",
    "STREAM_TERMINAL_TYPES",
    "parse_stream_event",
    "Response",
    "parse_event",
    "TextContent",
    "ThinkingContent",
    "ImageContent",
    "ToolCall",
    "UserMessage",
    "AssistantMessage",
    "ToolResultMessage",
    "BashExecutionMessage",
    "parse_message",
    "parse_messages",
    "message_text",
    "__version__",
]
