"""Tool argument validation against JSON Schema."""
from __future__ import annotations

from typing import Any

from .types import Tool, ToolCall


def validate_tool_call(tools: list[Tool], tool_call: ToolCall) -> dict[str, Any]:
    """Validate ``tool_call.arguments`` against the matching tool's JSON Schema.

    Finds the tool by name, then validates arguments using ``jsonschema``.
    Returns the (unchanged) arguments dict on success.
    Raises ``ValueError`` if the tool is not found or validation fails,
    with a human-readable message suitable for returning to the model as a
    tool error result.

    Usage in an agentic loop::

        try:
            args = validate_tool_call(context.tools, tool_call)
            result = await execute_tool(tool_call.name, args)
        except ValueError as e:
            context.messages.append(ToolResultMessage(
                tool_call_id=tool_call.id,
                tool_name=tool_call.name,
                content=[TextContent(text=str(e))],
                is_error=True,
            ))
    """
    tool = next((t for t in tools if t.name == tool_call.name), None)
    if tool is None:
        raise ValueError(f'Tool "{tool_call.name}" not found')

    try:
        import jsonschema  # type: ignore[import]
    except ImportError:
        raise ImportError(
            "validate_tool_call requires jsonschema: pip install jsonschema"
        )

    args = dict(tool_call.arguments)
    try:
        jsonschema.validate(instance=args, schema=tool.parameters)
    except jsonschema.ValidationError as exc:
        path = ".".join(str(p) for p in exc.absolute_path) or "root"
        raise ValueError(
            f'Validation failed for tool "{tool_call.name}":\n'
            f"  - {path}: {exc.message}\n\n"
            f"Received arguments:\n{args}"
        ) from exc
    except jsonschema.SchemaError as exc:
        raise ValueError(
            f'Invalid schema for tool "{tool_call.name}": {exc.message}'
        ) from exc

    return args


def string_enum(
    values: list[str],
    *,
    description: str | None = None,
    default: str | None = None,
) -> dict[str, Any]:
    """Build a JSON Schema string-enum fragment compatible with all providers.

    Use this instead of ``{"enum": [...]}`` bare — some providers (e.g. Google)
    reject ``anyOf/const`` patterns generated by TypeScript tools; a plain
    ``{"type": "string", "enum": [...]}`` works everywhere.

    Example::

        tool = Tool(
            name="set_mode",
            description="Set operating mode",
            parameters={
                "type": "object",
                "properties": {
                    "mode": string_enum(["fast", "balanced", "accurate"],
                                       description="Processing mode"),
                },
                "required": ["mode"],
            },
        )
    """
    schema: dict[str, Any] = {"type": "string", "enum": list(values)}
    if description:
        schema["description"] = description
    if default is not None:
        schema["default"] = default
    return schema
